### ISSUE TITLE
沒有壹個更新時間嗎？

### ISSUE THREAD

**Issue by chennanpo** [Liby99/saemanga-rust#1]
妳的漫畫站很簡潔，我看著很舒服。。希望有個更新時間跟檢索頁面。。方便查看最新更新的漫畫

**Comment by Liby99** [comment]
承知しました。我会在这个版本加上这个功能的；我之前也想过做这个，但是问题主要是汉化组发布更新的时间有时也不是很固定在一周的某个时间，漫画也会因作者本人外出取材之类的原因而延迟。所以预测下次更新什么的就会不是很准确。如果您有什么主意的话也请多赐教つ﹏⊂

目前的话最新更新的漫画是在主页上的“发现”一栏的。不过确实没有显示更新时间就是了( •̥́ ˍ •̀ू )

**Comment by chennanpo** [comment]
我看到了發現裏就只有前10個，也沒有個更新日期顯示，怎麼樣也得搞個單獨的頁面展示個更新順序前50的。。最好加個日期，就按他們日期當時間就可以了。。

**Comment by Liby99** [comment]
Make sense. 那我在下一个版本加上这个哦。
